// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.DBConextion;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(DbtestContext))]
    [Migration("20230611040203_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webapi.Models.Launch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("DateLunch")
                        .HasColumnType("datetime");

                    b.Property<bool>("FirstRocketlaunch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("MissionID")
                        .HasColumnType("int(11)");

                    b.Property<int>("RocketID")
                        .HasColumnType("int(11)");

                    b.HasKey("ID");

                    b.HasIndex("MissionID");

                    b.HasIndex("RocketID");

                    b.ToTable("launch", (string)null);
                });

            modelBuilder.Entity("webapi.Models.Mission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("ID");

                    b.ToTable("mission", (string)null);
                });

            modelBuilder.Entity("webapi.Models.Rocket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int>("RateSucessRocket")
                        .HasColumnType("int");

                    b.Property<string>("RocketName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("ID");

                    b.ToTable("rocket", (string)null);
                });

            modelBuilder.Entity("webapi.Models.Launch", b =>
                {
                    b.HasOne("webapi.Models.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Models.Rocket", "Rocket")
                        .WithMany()
                        .HasForeignKey("RocketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Rocket");
                });
#pragma warning restore 612, 618
        }
    }
}
